- docs/src/index.md
- src/operators.jl
> Add documentation

- src/operators.jl
> Fix implementation on operators with mixed bc

- test/operators-without-bc.jl
- test/operators.jl
> Add and refine unit tests

- docs/make.jl
- docs/src/api.md
- docs/src/formula.md
- docs/src/index.md
- src/operators-without-bc.jl
- src/operators.jl
> Update docs for all methods

- docs/src/index.md
- test/operators-without-bc.jl
- test/operators.jl
> Example with nonconstant drift combining the forward/backword first differences

- docs/make.jl
- docs/src/derivations.md
> Cleanup formula page

- docs/src/index.md
> Add a KFE example for docs

- README.md
- docs/src/derivations.md
- docs/src/index.md
> Resolve layout issue in derivations page

- README.md
> Resolve layout issue and fix operators in readme.md

- docs/tex/discretized-differential-operator-derivation.tex
- docs/tex/hact.bib
> Complete TeX

- docs/tex/discretized-differential-operator-derivation.tex
> Add documentation for absorbing barrier conditions

- test/operators-without-bc.jl
- test/operators.jl
> Accurate unit tests for irregular grids

- README.md
- docs/examples/LCP_advanced.jmd
- docs/examples/LCP_simple.jmd
- docs/src/index.md
- src/SimpleDifferentialOperators.jl
- src/operators.jl
- test/operators-without-bc.jl
- test/operators.jl
> Rename `interior` to `interiornodes`

- docs/tex/discretized-differential-operator-derivation.tex
> Fix mixed barrier condition derivation

- docs/tex/discretized-differential-operator-derivation.tex
> Use correct $\Delta_-$/$\Delta_+$ definitions and derivations

- docs/tex/discretized-differential-operator-derivation.tex
> Add regular grid derivation

- .gitignore
- docs/src/index.md
- docs/tex/discretized-differential-operator-derivation.tex
> Appendix based on gaussian elimination and fix formula for L_2

- docs/tex/discretized-differential-operator-derivation.tex
> Fix formula for $L^B$ with mixed boundary conditions

- src/operators.jl
- test/operators.jl
Resolves #109 and resolves #110
> Fix implementation for $L^B$ with mixed boundary conditions

- docs/tex/discretized-differential-operator-derivation.tex
Resolves #114.
I am pretty sure that both formulas are correct (i.e. #126 is more of implementation issue?). But an extra review won't hurt!
> Add full derivation of $L_{1+}^B$ and $L_2^B$ in appendix

- docs/tex/discretized-differential-operator-derivation.tex
> Use banded/tridiag matrix in derivations

- docs/tex/discretized-differential-operator-derivation.tex
> Edits to derivation document

- Project.toml
- src/SimpleDifferentialOperators.jl
- src/operators.jl
- src/types.jl
- src/utilities/extrapolatetoboundary.jl
- test/operators.jl
- test/runbenchmarks.jl
- test/utilities/extrapolatetoboundary.jl
> Modify types for `Mixed` bcs

- src/operators.jl
- src/types.jl
- test/operators.jl
> Implementation for new mixed BC

- docs/examples/KFE.jmd
- docs/src/notebooks.md
> Add a notebook for Kolmogorov forward equations

- src/operators.jl
> No multiple dispatch

- docs/src/index.md
- src/SimpleDifferentialOperators.jl
- src/operators.jl
- src/types.jl
- src/utilities/extrapolatetoboundary.jl
- test/operators.jl
- test/utilities/extrapolatetoboundary.jl
> Homogenous absorbing barrier

- docs/tex/discretized-differential-operator-derivation.tex
> Correct mixed bc discretization derivation

- docs/tex/discretized-differential-operator-derivation.tex
> Doc for jump diffusion

- docs/tex/discretized-differential-operator-derivation.tex
- src/SimpleDifferentialOperators.jl
- src/operators.jl
- test/operators-jump.jl
> Jump process operator on the interior implementation

- docs/src/index.md
> Jump diffusion example in package docs

- docs/tex/discretized-differential-operator-derivation.tex
> Math for models with continuous AND discrete states when bcs are applied

- docs/tex/discretized-differential-operator-derivation.tex
> Math for models with continuous AND discrete states 

- docs/tex/discretized-differential-operator-derivation.tex
> Math fix for models with continuous AND discrete states when bcs are applied 

- docs/src/index.md
> Jump diffusion package docs fix

- docs/examples/LCP_jump_diffusion.jmd
- docs/src/notebooks.md
> LCP notebook for jump diffusion

- docs/tex/discretized-differential-operator-derivation.tex
> Math for interior solutions with affine boundary operators

- src/SimpleDifferentialOperators.jl
- src/affine.jl
- src/operators.jl
- src/types.jl
- src/utilities/extrapolatetoboundary.jl
- test/affine.jl
- test/runtests.jl
- test/utilities/extrapolatetoboundary.jl
> Code for interior solutions with affine boundary operators 

- docs/src/examples.md
> `affineboundary` examples in package docs

- docs/tex/discretized-differential-operator-derivation.tex
> Complete math for absorbing barriers in even further interior nodes

- README.md
> Use Github markdown rendering for math in README
